language: java
jdk:
  - openjdk11

branches:
  only:
    - main

#1
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - gmelddl514@gmail.com


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: gongmoa-deploy # 6-3-3에서 생성한 S3 버킷
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: kimchan123/GongMoa #Github 주소
      branch: main