spring:
  datasource:
    url: jdbc:mariadb://springbootgongmoa.cyvztvefpz51.us-east-2.rds.amazonaws.com:3306/gongmoa
    username: ENC(AE8GnX8RjKPKglfjPeELk3RZhhBGsV7/)
    password: ENC(B7TzSzEsEU7aka2Gg+LT7DptXphjSlwM)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  profiles:
    include: oauth

logging.level:
  org.hibernate.SQL: debug


jasypt:
  encryptor:
    bean: encryptorBean

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/gongmoa
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver